CREATE TABLE IF NOT EXISTS senafoi26_users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  matricule VARCHAR(20) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  nom VARCHAR(120) NOT NULL,
  prenom VARCHAR(160) NOT NULL,
  contact VARCHAR(40) DEFAULT NULL,
  photo TEXT DEFAULT NULL,
  access_json JSON DEFAULT NULL,
  actif TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_senafoi26_users_matricule (matricule)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
